[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive", "rc"] }
bincode = "=1.3.3"
rand = "0.9.0"

[build-dependencies]
bindgen = "0.70.1"
cmake = "0.1.52"
